jobs:
- job: 'macOS'
  pool:
    vmImage: 'macOS-10.13' #'Ubuntu-16.04' # other options: 'macOS-10.13', 'VS2017-Win2016'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.6'
      Python36:
        python.version: '3.7'
    maxParallel: 3

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: pip install -r requirements-build.txt
    displayName: 'Install requirements'

  - script: python atest/run.py python atest/robot
    displayName: 'Running Acceptance Tests'

  - script: python utest/run.py python atest/robot
    displayName: 'Running Unit Tests'
